CREATE TABLE task (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE subtask (
    id SERIAL PRIMARY KEY,
    description TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    taskId INTEGER NOT NULL,
    CONSTRAINT fk_task FOREIGN KEY (taskId) REFERENCES task(id) ON DELETE CASCADE
);
